<?php
@system("clear");
//colors
$red="\033[1;31m";
$green="\033[1;32m";
$yellow="\033[1;33m";
$blue="\033[1;34m";
$res="\033[1;35m";
$nau="\033[1;36m";
$while="\033[1;37m";

echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Bắt đầu cài đặt Root...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("pkg install sudo");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Khởi động cập nhập hệ thống...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("apt-get update");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Khởi động cài đặt Git...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("apt-get install git");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Khởi động cài đặt Curl...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("sudo apt install curl");
@system("sudo apt install curl build-essential");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Khởi động cài đặt Node...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -");
@system("sudo apt install nodejs");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Kết nối tới Github...\n");
echo $nau,("-------------------------\n");
sleep (3);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Cài đặt C3C BOT...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("git clone https://github.com/lequanglam/c3c");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Bắt đầu cài đặt node_modems...\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
@system("cd c3c");
@system("sudo npm i");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Đang mở getConfig.js...\n(ctr+x để lưu dữ liệu)\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
sleep (2);
@system("sudo nano getConfig.js");
echo (" \n");
echo $nau,("-------------------------");
echo $green,("Hoàn tất !");
echo $nau,("-------------------------");
sleep (2);
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Cảm ơn bạn đã sử dụng sản phẩm của C3C, bot của bạn đã được cài đặt.\n");
echo $green,("Bạn có muốn khởi động Bot không?\n(Nhấn *enter* để khởi động hoặc *ctr+c* để dừng lại)\n");
echo $nau,("-------------------------\n");
readline();
@system("clear");
echo $blue,("Chào mừng bạn đến với C3C BOT\n");
echo $nau,("-------------------------\n");
echo $green,("Đang khởi động C3C Bot...\n(ctr+c để tắt Bot)\n");
echo $nau,("-------------------------\n");
echo $green,(" ");
sleep (2);
@system("npm start");
?>